export const perfumes = [
  {
    id: 1,
    name: "Perfect Pear",
    type: "Floral Frutado",
    price: 349.90,
    gender: "Feminino",
    class: "Trabalho",
    volume: "100ml",
    sac: "0800-456-7890",
    seals: ["Cruelty Free", "Vegan", "Eco-friendly"],
    approvals: ["ANVISA Processo nº 25351.000001/2024-01", "IFRA Certified"],
    description: "Inspirado no frescor de um pomar ao amanhecer, o Perfect Pear é o equilíbrio perfeito entre a doçura e a sofisticação.",
    ingredients: ["Pera", "Maçã Verde", "Lírio-do-vale"],
    usageNotes: "Ideal para dias ensolarados e ambientes de trabalho.",
    image: "/assets/perfumes/perfect_pear.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Perfect Pear."
  },
  {
    id: 2,
    name: "Neblina Noturna",
    type: "Eau de Parfum",
    price: 489.00,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    sac: "0800-456-7890",
    seals: ["Long Lasting", "Premium Collection"],
    approvals: ["ANVISA Processo nº 25351.000002/2024-02", "Quality Seal ISO 9001"],
    description: "Inspirado no silêncio da noite, este perfume combina o frescor do orvalho matinal com notas profundas de couro.",
    ingredients: ["Bergamota", "Couro Nobre", "Folhas de Cedro"],
    usageNotes: "Perfeito para eventos noturnos e ocasiões especiais.",
    image: "/assets/perfumes/neblina_noturna.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Neblina Noturna."
  },
  {
    id: 3,
    name: "Brise d'Or",
    type: "Colônia Premium",
    price: 279.00,
    gender: "Feminino",
    class: "Aquático",
    volume: "100ml",
    sac: "0800-456-7890",
    seals: ["Summer Fresh", "Marine Active"],
    approvals: ["ANVISA Processo nº 25351.000003/2024-03"],
    description: "Uma explosão cítrica e floral que remete ao sol mediterrâneo. Leveza e frescor em cada borrifada.",
    ingredients: ["Néroli", "Flor de Laranjeira", "Musgo de Carvalho"],
    usageNotes: "Excelente para o uso diário e momentos de lazer.",
    image: "/assets/perfumes/brise_dor.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Brise d'Or."
  },
  {
    id: 4,
    name: "Noir Intenso",
    type: "Parfum Intense",
    price: 529.90,
    gender: "Masculino",
    class: "Balada",
    volume: "100ml",
    sac: "0800-456-7890",
    seals: ["Intensity Max", "Night Aura"],
    approvals: ["ANVISA Processo nº 25351.000004/2024-04", "Global Quality"],
    description: "Uma fragrância magnética que exala poder e sedução. Notas intensas para quem não quer passar despercebido.",
    ingredients: ["Pimenta Preta", "Âmbar", "Baunilha"],
    usageNotes: "A escolha definitiva para baladas e festas.",
    image: "/assets/perfumes/noir_intenso.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Noir Intenso."
  },
  {
    id: 5,
    name: "Cedro Imperial",
    type: "Amadeirado Especiado",
    price: 399.90,
    gender: "Masculino",
    class: "Trabalho",
    volume: "100ml",
    sac: "0800-456-7890",
    seals: ["Wood Essence", "Corporate Essential"],
    approvals: ["ANVISA Processo nº 25351.000005/2024-05"],
    description: "Uma assinatura olfativa forte e presente, unindo a robustez do cedro com especiarias frias.",
    ingredients: ["Madeira de Cedro", "Pimenta Rosa", "Vetiver"],
    usageNotes: "Ideal para reuniões importantes e uso corporativo.",
    image: "/assets/perfumes/cedro_imperial.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Cedro Imperial."
  },
  {
    id: 6,
    name: "Flor de Lótus",
    type: "Floral Aquático",
    price: 329.90,
    gender: "Feminino",
    class: "Aquático",
    volume: "100ml",
    sac: "0800-456-7890",
    seals: ["Crystal Clear", "Zen Spirit"],
    approvals: ["ANVISA Processo nº 25351.000006/2024-06"],
    description: "A delicadeza da flor de lótus flutuando em águas cristalinas. Uma nuvem de frescor e feminilidade.",
    ingredients: ["Lótus", "Muguet", "Almíscar Branco"],
    usageNotes: "Perfeito para dias quentes de verão.",
    image: "/assets/perfumes/flor_de_lotus.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Flor de Lótus."
  },
  {
    id: 7,
    name: "Oud Supremo",
    type: "Oriental Amadeirado",
    price: 689.00,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    sac: "0800-456-7890",
    seals: ["Oud Gold", "Ultra Luxury"],
    approvals: ["ANVISA Processo nº 25351.000007/2024-07", "Privée Collection"],
    description: "O mais puro óleo de Agarwood misturado com resinas quentes. Um perfume para quem aprecia o luxo.",
    ingredients: ["Oud", "Incenso", "Sândalo"],
    usageNotes: "Reservado para eventos de gala e noites especiais.",
    image: "/assets/perfumes/oud_supremo.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Oud Supremo."
  },
  {
    id: 8,
    name: "Baunilha Dourada",
    type: "Oriental Gourmand",
    price: 419.00,
    gender: "Feminino",
    class: "Balada",
    volume: "100ml",
    sac: "0800-456-7890",
    seals: ["Feminine Glow", "Long Lasting"],
    approvals: ["ANVISA Processo nº 25351.000008/2024-08"],
    description: "Uma releitura sofisticada da baunilha, com toques de caramelo tostado e especiarias quentes.",
    ingredients: ["Fava Tonka", "Baunilha de Madagascar", "Patchouli"],
    usageNotes: "A arma secreta para encontros e festas sofisticadas.",
    image: "/assets/perfumes/baunilha_dourada.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre a Baunilha Dourada."
  },
  {
    id: 9,
    name: "Cítrico Safira",
    type: "Cítrico Aromático",
    price: 259.00,
    gender: "Masculino",
    class: "Aquático",
    volume: "100ml",
    sac: "0800-456-7890",
    seals: ["Energy Boost", "Daily Active"],
    approvals: ["ANVISA Processo nº 25351.000009/2024-09"],
    description: "Uma explosão de energia. O toque gelado da menta misturado aos limões sicilianos.",
    ingredients: ["Limão Siciliano", "Hortelã", "Gengibre"],
    usageNotes: "Para o dia a dia, academia e passeios ao ar livre.",
    image: "/assets/perfumes/citrico_safira.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Cítrico Safira."
  },
  {
    id: 10,
    name: "Rosa Negra",
    type: "Floral Chipre",
    price: 549.90,
    gender: "Feminino",
    class: "Noturno",
    volume: "100ml",
    sac: "0800-456-7890",
    seals: ["Mystery Rose", "Velvet Touch"],
    approvals: ["ANVISA Processo nº 25351.000010/2024-10"],
    description: "A rainha das flores em sua versão mais sombria e sedutora. Um perfume de rastro inconfundível.",
    ingredients: ["Rosa Búlgara", "Madeira de Oud", "Açafrão"],
    usageNotes: "Apenas para ocasiões onde você deseja ser o centro das atenções.",
    image: "/assets/perfumes/rosa_negra.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre a Rosa Negra."
  },
  {
    id: 11,
    name: "Ambar Royale",
    type: "Oriental Ambarado",
    price: 499.00,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    sac: "0800-456-7890",
    seals: ["Royal Ambar", "Deep Scent"],
    approvals: ["ANVISA Processo nº 25351.000011/2024-11"],
    description: "Uma composição majestosa de âmbar e madeiras nobres, feita para o homem clássico e imponente.",
    ingredients: ["Âmbar Cinzento", "Patchouli", "Couro"],
    usageNotes: "Ideal para climas frios e eventos formais.",
    image: "/assets/perfumes/cedro_imperial.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Ambar Royale."
  },
  {
    id: 12,
    name: "Jasmim de Seda",
    type: "Floral Branco",
    price: 369.00,
    gender: "Feminino",
    class: "Trabalho",
    volume: "100ml",
    sac: "0800-456-7890",
    seals: ["Silk Touch", "Pure Floral"],
    approvals: ["ANVISA Processo nº 25351.000012/2024-12"],
    description: "A pureza do jasmim em uma base sedosa de almíscar. Uma fragrância limpa e extremamente elegante.",
    ingredients: ["Jasmim Sambac", "Gardênia", "Almíscar"],
    usageNotes: "Macia e discreta, ideal para o dia a dia elegante.",
    image: "/assets/perfumes/perfect_pear.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jasmim de Seda."
  }
];
