export const perfumes = [
{
    id: 1,
    name: "Perfect Pear",
    type: "Floral Frutado",
    price: 349.90,
    gender: "Feminino",
    class: "Trabalho",
    volume: "100ml",
    sac: "+55 15 99847-8705",
    seals: ["Cruelty Free", "Vegan", "Eco-friendly"],
    approvals: ["ANVISA Processo nº 25351.000001/2024-01", "IFRA Certified"],
    description: "Inspirado no frescor de um pomar ao amanhecer, o Perfect Pear é o equilíbrio perfeito entre a doçura e a sofisticação.",
    ingredients: ["Pera", "Maçã Verde", "Lírio-do-vale"],
    usageNotes: "Ideal para dias ensolarados e ambientes de trabalho.",
    image: "/assets/perfumes/perfect_pear.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Perfect Pear."
  },
  {
    id: 2,
    name: "Neblina Noturna",
    type: "Eau de Parfum",
    price: 489.00,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    sac: "+55 15 99847-8705",
    seals: ["Long Lasting", "Premium Collection"],
    approvals: ["ANVISA Processo nº 25351.000002/2024-02", "Quality Seal ISO 9001"],
    description: "Inspirado no silêncio da noite, este perfume combina o frescor do orvalho matinal com notas profundas de couro.",
    ingredients: ["Bergamota", "Couro Nobre", "Folhas de Cedro"],
    usageNotes: "Perfeito para eventos noturnos e ocasiões especiais.",
    image: "/assets/perfumes/neblina_noturna.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Neblina Noturna."
  },
  {
    id: 3,
    name: "Brise d'Or",
    type: "Colônia Premium",
    price: 279.00,
    gender: "Feminino",
    class: "Aquático",
    volume: "100ml",
    sac: "+55 15 99847-8705",
    seals: ["Summer Fresh", "Marine Active"],
    approvals: ["ANVISA Processo nº 25351.000003/2024-03"],
    description: "Uma explosão cítrica e floral que remete ao sol mediterrâneo. Leveza e frescor em cada borrifada.",
    ingredients: ["Néroli", "Flor de Laranjeira", "Musgo de Carvalho"],
    usageNotes: "Excelente para o uso diário e momentos de lazer.",
    image: "/assets/perfumes/brise_dor.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Brise d'Or."
  },
  {
    id: 4,
    name: "Noir Intenso",
    type: "Parfum Intense",
    price: 529.90,
    gender: "Masculino",
    class: "Balada",
    volume: "100ml",
    sac: "+55 15 99847-8705",
    seals: ["Intensity Max", "Night Aura"],
    approvals: ["ANVISA Processo nº 25351.000004/2024-04", "Global Quality"],
    description: "Uma fragrância magnética que exala poder e sedução. Notas intensas para quem não quer passar despercebido.",
    ingredients: ["Pimenta Preta", "Âmbar", "Baunilha"],
    usageNotes: "A escolha definitiva para baladas e festas.",
    image: "/assets/perfumes/noir_intenso.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Noir Intenso."
  },
  {
    id: 5,
    name: "Cedro Imperial",
    type: "Amadeirado Especiado",
    price: 399.90,
    gender: "Masculino",
    class: "Trabalho",
    volume: "100ml",
    sac: "+55 15 99847-8705",
    seals: ["Wood Essence", "Corporate Essential"],
    approvals: ["ANVISA Processo nº 25351.000005/2024-05"],
    description: "Uma assinatura olfativa forte e presente, unindo a robustez do cedro com especiarias frias.",
    ingredients: ["Madeira de Cedro", "Pimenta Rosa", "Vetiver"],
    usageNotes: "Ideal para reuniões importantes e uso corporativo.",
    image: "/assets/perfumes/cedro_imperial.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Cedro Imperial."
  },
  {
    id: 6,
    name: "Flor de Lótus",
    type: "Floral Aquático",
    price: 329.90,
    gender: "Feminino",
    class: "Aquático",
    volume: "100ml",
    sac: "+55 15 99847-8705",
    seals: ["Crystal Clear", "Zen Spirit"],
    approvals: ["ANVISA Processo nº 25351.000006/2024-06"],
    description: "A delicadeza da flor de lótus flutuando em águas cristalinas. Uma nuvem de frescor e feminilidade.",
    ingredients: ["Lótus", "Muguet", "Almíscar Branco"],
    usageNotes: "Perfeito para dias quentes de verão.",
    image: "/assets/perfumes/flor_de_lotus.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Flor de Lótus."
  },
  {
    id: 7,
    name: "Oud Supremo",
    type: "Oriental Amadeirado",
    price: 689.00,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    sac: "+55 15 99847-8705",
    seals: ["Oud Gold", "Ultra Luxury"],
    approvals: ["ANVISA Processo nº 25351.000007/2024-07", "Privée Collection"],
    description: "O mais puro óleo de Agarwood misturado com resinas quentes. Um perfume para quem aprecia o luxo.",
    ingredients: ["Oud", "Incenso", "Sândalo"],
    usageNotes: "Reservado para eventos de gala e noites especiais.",
    image: "/assets/perfumes/oud_supremo.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Oud Supremo."
  },
  {
    id: 8,
    name: "Baunilha Dourada",
    type: "Oriental Gourmand",
    price: 419.00,
    gender: "Feminino",
    class: "Balada",
    volume: "100ml",
    sac: "+55 15 99847-8705",
    seals: ["Feminine Glow", "Long Lasting"],
    approvals: ["ANVISA Processo nº 25351.000008/2024-08"],
    description: "Uma releitura sofisticada da baunilha, com toques de caramelo tostado e especiarias quentes.",
    ingredients: ["Fava Tonka", "Baunilha de Madagascar", "Patchouli"],
    usageNotes: "A arma secreta para encontros e festas sofisticadas.",
    image: "/assets/perfumes/baunilha_dourada.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre a Baunilha Dourada."
  },
  {
    id: 9,
    name: "Cítrico Safira",
    type: "Cítrico Aromático",
    price: 259.00,
    gender: "Masculino",
    class: "Aquático",
    volume: "100ml",
    sac: "+55 15 99847-8705",
    seals: ["Energy Boost", "Daily Active"],
    approvals: ["ANVISA Processo nº 25351.000009/2024-09"],
    description: "Uma explosão de energia. O toque gelado da menta misturado aos limões sicilianos.",
    ingredients: ["Limão Siciliano", "Hortelã", "Gengibre"],
    usageNotes: "Para o dia a dia, academia e passeios ao ar livre.",
    image: "/assets/perfumes/citrico_safira.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Cítrico Safira."
  },
  {
    id: 10,
    name: "Rosa Negra",
    type: "Floral Chipre",
    price: 549.90,
    gender: "Feminino",
    class: "Noturno",
    volume: "100ml",
    sac: "+55 15 99847-8705",
    seals: ["Mystery Rose", "Velvet Touch"],
    approvals: ["ANVISA Processo nº 25351.000010/2024-10"],
    description: "A rainha das flores em sua versão mais sombria e sedutora. Um perfume de rastro inconfundível.",
    ingredients: ["Rosa Búlgara", "Madeira de Oud", "Açafrão"],
    usageNotes: "Apenas para ocasiões onde você deseja ser o centro das atenções.",
    image: "/assets/perfumes/rosa_negra.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre a Rosa Negra."
  },
  {
    id: 11,
    name: "Ambar Royale",
    type: "Oriental Ambarado",
    price: 499.00,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    sac: "+55 15 99847-8705",
    seals: ["Royal Ambar", "Deep Scent"],
    approvals: ["ANVISA Processo nº 25351.000011/2024-11"],
    description: "Uma composição majestosa de âmbar e madeiras nobres, feita para o homem clássico e imponente.",
    ingredients: ["Âmbar Cinzento", "Patchouli", "Couro"],
    usageNotes: "Ideal para climas frios e eventos formais.",
    image: "/assets/perfumes/cedro_imperial.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Ambar Royale."
  },
  {
    id: 12,
    name: "Jasmim de Seda",
    type: "Floral Branco",
    price: 369.00,
    gender: "Feminino",
    class: "Trabalho",
    volume: "100ml",
    sac: "+55 15 99847-8705",
    seals: ["Silk Touch", "Pure Floral"],
    approvals: ["ANVISA Processo nº 25351.000012/2024-12"],
    description: "A pureza do jasmim em uma base sedosa de almíscar. Uma fragrância limpa e extremamente elegante.",
    ingredients: ["Jasmim Sambac", "Gardênia", "Almíscar"],
    usageNotes: "Macia e discreta, ideal para o dia a dia elegante.",
    image: "/assets/perfumes/perfect_pear.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jasmim de Seda."
  },
  {
    id: 13,
    name: "Paco Rabanne Invictus",
    brand: "Paco Rabanne",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Paco Rabanne.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/paco_rabanne_invictus.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Paco Rabanne Invictus."
  },
  {
    id: 14,
    name: "Paco Rabanne Invictus Victory",
    brand: "Paco Rabanne",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Paco Rabanne.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/paco_rabanne_invictus_victory.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Paco Rabanne Invictus Victory."
  },
  {
    id: 15,
    name: "Paco Rabanne Invictus Parfum",
    brand: "Paco Rabanne",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Paco Rabanne.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/paco_rabanne_invictus_parfum.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Paco Rabanne Invictus Parfum."
  },
  {
    id: 16,
    name: "Paco Rabanne One Million Cologne",
    brand: "Paco Rabanne",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "125ml",
    availableVolumes: ["125ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Paco Rabanne.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/paco_rabanne_one_million_cologne.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Paco Rabanne One Million Cologne."
  },
  {
    id: 17,
    name: "Paco Rabanne One Million Elixir",
    brand: "Paco Rabanne",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Paco Rabanne.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/paco_rabanne_one_million_elixir.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Paco Rabanne One Million Elixir."
  },
  {
    id: 18,
    name: "Paco Rabanne One Million Royal",
    brand: "Paco Rabanne",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Paco Rabanne.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/paco_rabanne_one_million_royal.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Paco Rabanne One Million Royal."
  },
  {
    id: 19,
    name: "Paco Rabanne One Million Parfum",
    brand: "Paco Rabanne",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Paco Rabanne.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/paco_rabanne_one_million_parfum.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Paco Rabanne One Million Parfum."
  },
  {
    id: 20,
    name: "Paco Rabanne One Million",
    brand: "Paco Rabanne",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Paco Rabanne.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/paco_rabanne_one_million.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Paco Rabanne One Million."
  },
  {
    id: 21,
    name: "Paco Rabanne Lucky",
    brand: "Paco Rabanne",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Paco Rabanne.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/paco_rabanne_lucky.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Paco Rabanne Lucky."
  },
  {
    id: 22,
    name: "Paco Rabanne Phantom",
    brand: "Paco Rabanne",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "150ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Paco Rabanne.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/paco_rabanne_phantom.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Paco Rabanne Phantom."
  },
  {
    id: 23,
    name: "Paco Rabanne Phantom Parfum",
    brand: "Paco Rabanne",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "150ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Paco Rabanne.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/paco_rabanne_phantom_parfum.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Paco Rabanne Phantom Parfum."
  },
  {
    id: 24,
    name: "Paco Rabanne Pure XS",
    brand: "Paco Rabanne",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Paco Rabanne.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/paco_rabanne_pure_xs.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Paco Rabanne Pure XS."
  },
  {
    id: 25,
    name: "Carolina Herrera Gold Fantasy",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_gold_fantasy.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera Gold Fantasy."
  },
  {
    id: 26,
    name: "Carolina Herrera Bad Boy",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_bad_boy.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera Bad Boy."
  },
  {
    id: 27,
    name: "Carolina Herrera Bad Boy Cobalt",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_bad_boy_cobalt.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera Bad Boy Cobalt."
  },
  {
    id: 28,
    name: "Carolina Herrera Bad Boy Dazzling Garden",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_bad_boy_dazzling_garden.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera Bad Boy Dazzling Garden."
  },
  {
    id: 29,
    name: "Carolina Herrera Bad Boy Sparkling Ice",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_bad_boy_sparkling_ice.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera Bad Boy Sparkling Ice."
  },
  {
    id: 30,
    name: "Carolina Herrera Bad Boy Extreme",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_bad_boy_extreme.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera Bad Boy Extreme."
  },
  {
    id: 31,
    name: "Carolina Herrera 212 VIP Black",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_212_vip_black.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera 212 VIP Black."
  },
  {
    id: 32,
    name: "Carolina Herrera 212 VIP Black MTV",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    availableVolumes: ["100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_212_vip_black_mtv.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera 212 VIP Black MTV."
  },
  {
    id: 33,
    name: "Carolina Herrera 212 VIP Black Elixir",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_212_vip_black_elixir.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera 212 VIP Black Elixir."
  },
  {
    id: 34,
    name: "Carolina Herrera 212 VIP Red",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_212_vip_red.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera 212 VIP Red."
  },
  {
    id: 35,
    name: "Carolina Herrera 212 VIP MTV",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    availableVolumes: ["100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_212_vip_mtv.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera 212 VIP MTV."
  },
  {
    id: 36,
    name: "Carolina Herrera 212 Men NYC",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_212_men_nyc.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera 212 Men NYC."
  },
  {
    id: 37,
    name: "Carolina Herrera Herrera for Men",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    availableVolumes: ["100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_herrera_for_men.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera Herrera for Men."
  },
  {
    id: 38,
    name: "Carolina Herrera 212 Men Heroes Forever Young",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "90ml", "150ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_212_men_heroes_forever_young.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera 212 Men Heroes Forever Young."
  },
  {
    id: 39,
    name: "Carolina Herrera CH Men",
    brand: "Carolina Herrera",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Carolina Herrera.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/carolina_herrera_ch_men.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Carolina Herrera CH Men."
  },
  {
    id: 40,
    name: "Jean Paul Gaultier Scandal Absolu",
    brand: "Jean Paul Gaultier",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "150ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Jean Paul Gaultier.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/jean_paul_gaultier_scandal_absolu.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jean Paul Gaultier Scandal Absolu."
  },
  {
    id: 41,
    name: "Jean Paul Gaultier Scandal",
    brand: "Jean Paul Gaultier",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "150ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Jean Paul Gaultier.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/jean_paul_gaultier_scandal.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jean Paul Gaultier Scandal."
  },
  {
    id: 42,
    name: "Jean Paul Gaultier Scandal Le Parfum",
    brand: "Jean Paul Gaultier",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Jean Paul Gaultier.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/jean_paul_gaultier_scandal_le_parfum.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jean Paul Gaultier Scandal Le Parfum."
  },
  {
    id: 43,
    name: "Jean Paul Gaultier Scandal Intense",
    brand: "Jean Paul Gaultier",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Jean Paul Gaultier.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/jean_paul_gaultier_scandal_intense.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jean Paul Gaultier Scandal Intense."
  },
  {
    id: 44,
    name: "Jean Paul Gaultier Le Beau",
    brand: "Jean Paul Gaultier",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "75ml",
    availableVolumes: ["75ml", "125ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Jean Paul Gaultier.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/jean_paul_gaultier_le_beau.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jean Paul Gaultier Le Beau."
  },
  {
    id: 45,
    name: "Jean Paul Gaultier Le Male",
    brand: "Jean Paul Gaultier",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "75ml",
    availableVolumes: ["75ml", "125ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Jean Paul Gaultier.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/jean_paul_gaultier_le_male.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jean Paul Gaultier Le Male."
  },
  {
    id: 46,
    name: "Jean Paul Gaultier Ultra Male",
    brand: "Jean Paul Gaultier",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "75ml",
    availableVolumes: ["75ml", "125ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Jean Paul Gaultier.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/jean_paul_gaultier_ultra_male.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jean Paul Gaultier Ultra Male."
  },
  {
    id: 47,
    name: "Jean Paul Gaultier Le Male Le Parfum",
    brand: "Jean Paul Gaultier",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "75ml",
    availableVolumes: ["75ml", "125ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Jean Paul Gaultier.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/jean_paul_gaultier_le_male_le_parfum.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jean Paul Gaultier Le Male Le Parfum."
  },
  {
    id: 48,
    name: "Jean Paul Gaultier Le Male Elixir",
    brand: "Jean Paul Gaultier",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "75ml",
    availableVolumes: ["75ml", "125ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Jean Paul Gaultier.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/jean_paul_gaultier_le_male_elixir.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jean Paul Gaultier Le Male Elixir."
  },
  {
    id: 49,
    name: "Jean Paul Gaultier Le Beau Paradise Garden",
    brand: "Jean Paul Gaultier",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "75ml",
    availableVolumes: ["75ml", "125ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Jean Paul Gaultier.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/jean_paul_gaultier_le_beau_paradise_garden.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jean Paul Gaultier Le Beau Paradise Garden."
  },
  {
    id: 50,
    name: "Maison Francis Kurkdjian Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Maison Francis Kurkdjian.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/maison_francis_kurkdjian_baccarat_rouge_540.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Maison Francis Kurkdjian Baccarat Rouge 540."
  },
  {
    id: 51,
    name: "Dior Sauvage",
    brand: "Dior",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    availableVolumes: ["100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Dior.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/dior_sauvage.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Dior Sauvage."
  },
  {
    id: 52,
    name: "Dior Fahrenheit",
    brand: "Dior",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    availableVolumes: ["100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Dior.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/dior_fahrenheit.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Dior Fahrenheit."
  },
  {
    id: 53,
    name: "Dior Dior Homme",
    brand: "Dior",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    availableVolumes: ["100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Dior.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/dior_dior_homme.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Dior Dior Homme."
  },
  {
    id: 54,
    name: "Chanel Allure Homme",
    brand: "Chanel",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "150ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Chanel.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/chanel_allure_homme.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Chanel Allure Homme."
  },
  {
    id: 55,
    name: "Chanel Platinum Egoiste",
    brand: "Chanel",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Chanel.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/chanel_platinum_egoiste.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Chanel Platinum Egoiste."
  },
  {
    id: 56,
    name: "Chanel Bleu de Chanel",
    brand: "Chanel",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Chanel.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/chanel_bleu_de_chanel.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Chanel Bleu de Chanel."
  },
  {
    id: 57,
    name: "Chanel Allure Homme Sport",
    brand: "Chanel",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Chanel.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/chanel_allure_homme_sport.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Chanel Allure Homme Sport."
  },
  {
    id: 58,
    name: "Calvin Klein CK One Essence",
    brand: "Calvin Klein",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    availableVolumes: ["100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Calvin Klein.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/calvin_klein_ck_one_essence.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Calvin Klein CK One Essence."
  },
  {
    id: 59,
    name: "Calvin Klein CK One",
    brand: "Calvin Klein",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Calvin Klein.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/calvin_klein_ck_one.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Calvin Klein CK One."
  },
  {
    id: 60,
    name: "Calvin Klein CK Be",
    brand: "Calvin Klein",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    availableVolumes: ["100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Calvin Klein.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/calvin_klein_ck_be.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Calvin Klein CK Be."
  },
  {
    id: 61,
    name: "Calvin Klein CK One Shock",
    brand: "Calvin Klein",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    availableVolumes: ["100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Calvin Klein.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/calvin_klein_ck_one_shock.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Calvin Klein CK One Shock."
  },
  {
    id: 62,
    name: "Ralph Lauren Polo 67",
    brand: "Ralph Lauren",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "40ml",
    availableVolumes: ["40ml", "75ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Ralph Lauren.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/ralph_lauren_polo_67.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Ralph Lauren Polo 67."
  },
  {
    id: 63,
    name: "Ralph Lauren Polo Red",
    brand: "Ralph Lauren",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "75ml",
    availableVolumes: ["75ml", "125ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Ralph Lauren.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/ralph_lauren_polo_red.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Ralph Lauren Polo Red."
  },
  {
    id: 64,
    name: "Ralph Lauren Polo Blue",
    brand: "Ralph Lauren",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "75ml",
    availableVolumes: ["75ml", "125ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Ralph Lauren.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/ralph_lauren_polo_blue.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Ralph Lauren Polo Blue."
  },
  {
    id: 65,
    name: "Ralph Lauren Polo Green",
    brand: "Ralph Lauren",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "30ml",
    availableVolumes: ["30ml", "50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Ralph Lauren.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/ralph_lauren_polo_green.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Ralph Lauren Polo Green."
  },
  {
    id: 66,
    name: "Ralph Lauren Polo Sport",
    brand: "Ralph Lauren",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "125ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Ralph Lauren.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/ralph_lauren_polo_sport.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Ralph Lauren Polo Sport."
  },
  {
    id: 67,
    name: "Ralph Lauren Polo Black",
    brand: "Ralph Lauren",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "30ml",
    availableVolumes: ["30ml", "50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Ralph Lauren.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/ralph_lauren_polo_black.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Ralph Lauren Polo Black."
  },
  {
    id: 68,
    name: "Ferrari Ferrari Red",
    brand: "Ferrari",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "75ml",
    availableVolumes: ["75ml", "125ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Ferrari.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/ferrari_ferrari_red.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Ferrari Ferrari Red."
  },
  {
    id: 69,
    name: "Ferrari Ferrari Black",
    brand: "Ferrari",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Ferrari.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/ferrari_ferrari_black.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Ferrari Ferrari Black."
  },
  {
    id: 70,
    name: "Burberry Hero",
    brand: "Burberry",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Burberry.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/burberry_hero.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Burberry Hero."
  },
  {
    id: 71,
    name: "Azzaro Chrome",
    brand: "Azzaro",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Azzaro.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/azzaro_chrome.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Azzaro Chrome."
  },
  {
    id: 72,
    name: "Azzaro The Most Wanted",
    brand: "Azzaro",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "150ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Azzaro.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/azzaro_the_most_wanted.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Azzaro The Most Wanted."
  },
  {
    id: 73,
    name: "Azzaro Pour Homme",
    brand: "Azzaro",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "30ml",
    availableVolumes: ["30ml", "50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Azzaro.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/azzaro_pour_homme.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Azzaro Pour Homme."
  },
  {
    id: 74,
    name: "Dolce & Gabbana Pour Homme",
    brand: "Dolce & Gabbana",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "75ml",
    availableVolumes: ["75ml", "125ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Dolce & Gabbana.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/dolce___gabbana_pour_homme.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Dolce & Gabbana Pour Homme."
  },
  {
    id: 75,
    name: "Dolce & Gabbana Light Blue",
    brand: "Dolce & Gabbana",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "30ml",
    availableVolumes: ["30ml", "50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Dolce & Gabbana.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/dolce___gabbana_light_blue.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Dolce & Gabbana Light Blue."
  },
  {
    id: 76,
    name: "Dolce & Gabbana The One",
    brand: "Dolce & Gabbana",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "100ml",
    availableVolumes: ["100ml", "150ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Dolce & Gabbana.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/dolce___gabbana_the_one.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Dolce & Gabbana The One."
  },
  {
    id: 77,
    name: "Mont Blanc Starwalker",
    brand: "Mont Blanc",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Mont Blanc.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/mont_blanc_starwalker.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Mont Blanc Starwalker."
  },
  {
    id: 78,
    name: "Mont Blanc Explorer",
    brand: "Mont Blanc",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Mont Blanc.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/mont_blanc_explorer.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Mont Blanc Explorer."
  },
  {
    id: 79,
    name: "Viktor & Rolf Spicebomb",
    brand: "Viktor & Rolf",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "90ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Viktor & Rolf.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/viktor___rolf_spicebomb.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Viktor & Rolf Spicebomb."
  },
  {
    id: 80,
    name: "Jacques Bogart Silver Scent",
    brand: "Jacques Bogart",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "30ml",
    availableVolumes: ["30ml", "50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Jacques Bogart.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/jacques_bogart_silver_scent.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Jacques Bogart Silver Scent."
  },
  {
    id: 81,
    name: "Joop! Homme",
    brand: "Joop!",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "75ml",
    availableVolumes: ["75ml", "125ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Joop!.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/joop__homme.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Joop! Homme."
  },
  {
    id: 82,
    name: "Narciso Rodriguez Bleu Noir",
    brand: "Narciso Rodriguez",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Narciso Rodriguez.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/narciso_rodriguez_bleu_noir.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Narciso Rodriguez Bleu Noir."
  },
  {
    id: 83,
    name: "Lamborghini Huracan",
    brand: "Lamborghini",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "150ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Lamborghini.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/lamborghini_huracan.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Lamborghini Huracan."
  },
  {
    id: 84,
    name: "Givenchy Gentleman",
    brand: "Givenchy",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Givenchy.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/givenchy_gentleman.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Givenchy Gentleman."
  },
  {
    id: 85,
    name: "Nautica Voyage",
    brand: "Nautica",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Nautica.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/nautica_voyage.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Nautica Voyage."
  },
  {
    id: 86,
    name: "Giorgio Armani Acqua di Giò Profondo",
    brand: "Giorgio Armani",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "90ml",
    availableVolumes: ["90ml", "100ml", "150ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Giorgio Armani.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/giorgio_armani_acqua_di_gi__profondo.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Giorgio Armani Acqua di Giò Profondo."
  },
  {
    id: 87,
    name: "Giorgio Armani Armani Code",
    brand: "Giorgio Armani",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "75ml", "125ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Giorgio Armani.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/giorgio_armani_armani_code.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Giorgio Armani Armani Code."
  },
  {
    id: 88,
    name: "Giorgio Armani Acqua di Giò Pour Homme",
    brand: "Giorgio Armani",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "20ml",
    availableVolumes: ["20ml", "50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Giorgio Armani.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/giorgio_armani_acqua_di_gi__pour_homme.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Giorgio Armani Acqua di Giò Pour Homme."
  },
  {
    id: 89,
    name: "Bulgari Terrae Essence",
    brand: "Bulgari",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "60ml",
    availableVolumes: ["60ml", "100ml", "150ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Bulgari.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/bulgari_terrae_essence.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Bulgari Terrae Essence."
  },
  {
    id: 90,
    name: "Bulgari Rain Essence",
    brand: "Bulgari",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Bulgari.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/bulgari_rain_essence.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Bulgari Rain Essence."
  },
  {
    id: 91,
    name: "Bulgari Wood Essence",
    brand: "Bulgari",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "60ml",
    availableVolumes: ["60ml", "100ml", "150ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Bulgari.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/bulgari_wood_essence.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Bulgari Wood Essence."
  },
  {
    id: 92,
    name: "Bulgari Man in Black",
    brand: "Bulgari",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "60ml",
    availableVolumes: ["60ml", "100ml", "150ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Bulgari.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/bulgari_man_in_black.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Bulgari Man in Black."
  },
  {
    id: 93,
    name: "Bulgari Aqva",
    brand: "Bulgari",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Bulgari.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/bulgari_aqva.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Bulgari Aqva."
  },
  {
    id: 94,
    name: "Bulgari Glacial Essence",
    brand: "Bulgari",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "60ml",
    availableVolumes: ["60ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Bulgari.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/bulgari_glacial_essence.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Bulgari Glacial Essence."
  },
  {
    id: 95,
    name: "Animale Animale Gold",
    brand: "Animale",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "30ml",
    availableVolumes: ["30ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Animale.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/animale_animale_gold.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Animale Animale Gold."
  },
  {
    id: 96,
    name: "Animale Animale",
    brand: "Animale",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "30ml",
    availableVolumes: ["30ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Animale.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/animale_animale.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Animale Animale."
  },
  {
    id: 97,
    name: "Animale Animale S",
    brand: "Animale",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "30ml",
    availableVolumes: ["30ml", "50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Animale.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/animale_animale_s.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Animale Animale S."
  },
  {
    id: 98,
    name: "Nautica Blue",
    brand: "Nautica",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Nautica.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/nautica_blue.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Nautica Blue."
  },
  {
    id: 99,
    name: "Moschino Toy Boy",
    brand: "Moschino",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "30ml",
    availableVolumes: ["30ml", "50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Moschino.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/moschino_toy_boy.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Moschino Toy Boy."
  },
  {
    id: 100,
    name: "Lacoste L12 12",
    brand: "Lacoste",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Lacoste.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/lacoste_l12_12.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Lacoste L12 12."
  },
  {
    id: 101,
    name: "Versace The Dreamer",
    brand: "Versace",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Versace.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/versace_the_dreamer.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Versace The Dreamer."
  },
  {
    id: 102,
    name: "Versace Eros Flame",
    brand: "Versace",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Versace.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/versace_eros_flame.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Versace Eros Flame."
  },
  {
    id: 103,
    name: "Versace Pour Homme",
    brand: "Versace",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Versace.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/versace_pour_homme.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Versace Pour Homme."
  },
  {
    id: 104,
    name: "Versace Eros",
    brand: "Versace",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Versace.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/versace_eros.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Versace Eros."
  },
  {
    id: 105,
    name: "Versace Eros Energy",
    brand: "Versace",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Versace.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/versace_eros_energy.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Versace Eros Energy."
  },
  {
    id: 106,
    name: "Versace Dylan Blue",
    brand: "Versace",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "30ml",
    availableVolumes: ["30ml", "50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Versace.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/versace_dylan_blue.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Versace Dylan Blue."
  },
  {
    id: 107,
    name: "Antonio Banderas The Secret",
    brand: "Antonio Banderas",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Antonio Banderas.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/antonio_banderas_the_secret.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Antonio Banderas The Secret."
  },
  {
    id: 108,
    name: "Antonio Banderas The Golden Secret",
    brand: "Antonio Banderas",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Antonio Banderas.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/antonio_banderas_the_golden_secret.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Antonio Banderas The Golden Secret."
  },
  {
    id: 109,
    name: "Antonio Banderas The Icon Elixir",
    brand: "Antonio Banderas",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Antonio Banderas.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/antonio_banderas_the_icon_elixir.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Antonio Banderas The Icon Elixir."
  },
  {
    id: 110,
    name: "Antonio Banderas The Icon",
    brand: "Antonio Banderas",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Antonio Banderas.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/antonio_banderas_the_icon.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Antonio Banderas The Icon."
  },
  {
    id: 111,
    name: "Antonio Banderas The Secret Absolu",
    brand: "Antonio Banderas",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "50ml",
    availableVolumes: ["50ml", "100ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Antonio Banderas.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/antonio_banderas_the_secret_absolu.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Antonio Banderas The Secret Absolu."
  },
  {
    id: 112,
    name: "Diesel Only the Brave",
    brand: "Diesel",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "75ml",
    availableVolumes: ["75ml", "125ml", "200ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Diesel.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/diesel_only_the_brave.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Diesel Only the Brave."
  },
  {
    id: 113,
    name: "Diesel Spirit of the Brave",
    brand: "Diesel",
    type: "Eau de Parfum",
    price: 399.9,
    gender: "Masculino",
    class: "Noturno",
    volume: "125ml",
    availableVolumes: ["125ml"],
    sac: "+55 15 99847-8705",
    seals: ["Original", "Garantia PR"],
    approvals: ["ANVISA Processo nº ..."],
    description: "Uma fragrância sofisticada da Diesel.",
    ingredients: [],
    usageNotes: "Perfeito para todas as ocasiões.",
    image: "/assets/perfumes/diesel_spirit_of_the_brave.png",
    whatsappLink: "https://wa.me/5515996966772?text=Olá! Gostaria de saber mais sobre o Diesel Spirit of the Brave."
  }
];